import { Injectable } from '@nestjs/common';
import { DailyTransactionRepository } from '@infrastructure/repositories/daily-transaction.repository';
import { DefaultTransactionRepository } from '@infrastructure/repositories/default-transaction.repository';
import { PlanItemRepository } from '@infrastructure/repositories/planItem.repository';
import { PlanRepository } from '@infrastructure/repositories/plan.repository';
import { EXCLUDE_TYPE } from '@domain/entities/planItem/planItem.enum';
import { TransactionType } from '@domain/entities/daily-transaction/daily-transaction.entity';

@Injectable()
export class DefaultTransactionAutoGeneratorService {
  constructor(
    private readonly dailyTransactionRepository: DailyTransactionRepository,
    private readonly defaultTransactionRepository: DefaultTransactionRepository,
    private readonly planItemRepository: PlanItemRepository,
    private readonly planRepository: PlanRepository,
  ) {}

  /**
   * Tự động tạo daily transaction từ default transaction cho một planItem vào một ngày cụ thể
   * Chỉ tạo nếu chưa có daily transaction thủ công cho planItem đó trong ngày
   * @param planItemId ID của planItem
   * @param date Ngày cần tạo (format: YYYY-MM-DD)
   * @returns Số lượng transaction đã tạo
   */
  async generateDailyTransactionsFromDefaults(
    planItemId: string,
    date: string,
  ): Promise<number> {
    const planItem = await this.planItemRepository.findOne({
      where: { id: planItemId },
      relations: ['plan'],
    });

    if (!planItem || planItem.excludeType !== EXCLUDE_TYPE.FLEXIBLE) {
      return 0;
    }

    // Kiểm tra xem đã có daily transaction thủ công cho planItem này trong ngày chưa
    const existingTransactions = await this.dailyTransactionRepository.find({
      where: {
        planItemId,
        date,
        isDefaultGenerated: false, // Chỉ kiểm tra transaction thủ công
      },
    });

    // Nếu đã có transaction thủ công, không tạo từ default
    if (existingTransactions.length > 0) {
      return 0;
    }

    // Kiểm tra xem đã có transaction tự động từ default chưa (tránh duplicate)
    const existingAutoTransactions = await this.dailyTransactionRepository.find(
      {
        where: {
          planItemId,
          date,
          isDefaultGenerated: true,
        },
      },
    );

    if (existingAutoTransactions.length > 0) {
      return 0; // Đã tạo rồi
    }

    // Lấy tất cả default transactions enabled cho planItem này
    const defaultTransactions = await this.defaultTransactionRepository.find({
      where: {
        planItemId,
        enabled: true,
      },
    });

    if (defaultTransactions.length === 0) {
      return 0; // Không có default transaction, sẽ tính là 0
    }

    // Tạo daily transaction từ mỗi default transaction
    const plan = await this.planRepository.findOne({
      where: { id: planItem.planId },
    });

    if (!plan) {
      return 0;
    }

    let createdCount = 0;
    for (const defaultTx of defaultTransactions) {
      const dailyTransaction = this.dailyTransactionRepository.create({
        label: defaultTx.label,
        amount: defaultTx.amount,
        date,
        type:
          planItem.type === 'INCOME'
            ? TransactionType.INCOME
            : TransactionType.EXPENSE,
        planId: plan.id,
        planItemId: planItem.id,
        categoryId: planItem.categoryId,
        isDefaultGenerated: true, // Đánh dấu là tự động tạo
      });

      await this.dailyTransactionRepository.save(dailyTransaction);
      createdCount++;
    }

    return createdCount;
  }

  /**
   * Tự động tạo daily transaction từ default transaction cho tất cả FLEXIBLE planItems của một plan
   * @param planId ID của plan
   * @param date Ngày cần tạo (format: YYYY-MM-DD)
   * @returns Tổng số transaction đã tạo
   */
  async generateDailyTransactionsForPlan(
    planId: string,
    date: string,
  ): Promise<number> {
    const plan = await this.planRepository.findOne({
      where: { id: planId },
    });

    if (!plan) {
      return 0;
    }

    // Lấy tất cả FLEXIBLE planItems của plan
    const flexibleItems = await this.planItemRepository.find({
      where: {
        planId,
        excludeType: EXCLUDE_TYPE.FLEXIBLE,
      },
    });

    let totalCreated = 0;
    for (const item of flexibleItems) {
      const created = await this.generateDailyTransactionsFromDefaults(
        item.id,
        date,
      );
      totalCreated += created;
    }

    return totalCreated;
  }

  /**
   * Xóa các daily transaction tự động tạo từ default cho một planItem trong một ngày
   * (Khi user tạo transaction thủ công, cần xóa các transaction tự động)
   * @param planItemId ID của planItem
   * @param date Ngày cần xóa
   */
  async removeAutoGeneratedTransactions(
    planItemId: string,
    date: string,
  ): Promise<void> {
    await this.dailyTransactionRepository.delete({
      planItemId,
      date,
      isDefaultGenerated: true,
    });
  }
}
